# Generated by Django 5.1 on 2024-10-24 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0009_articlecomments_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomments',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
