# Generated by Django 5.1 on 2024-10-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0010_articlecomments_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomments',
            name='sent_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
