# Generated by Django 5.1 on 2024-10-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0011_alter_articlecomments_sent_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomments',
            old_name='sent_date',
            new_name='created',
        ),
    ]
