# Generated by Django 5.1 on 2024-12-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0015_article_saved_by_users_alter_article_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='saved_by_users',
        ),
        migrations.DeleteModel(
            name='SavedArticles',
        ),
    ]
