# Generated by Django 5.1 on 2025-01-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0016_remove_article_saved_by_users_delete_savedarticles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomments',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
