# Generated by Django 5.1 on 2025-01-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0017_alter_articlecomments_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=False, upload_to='articles_pic'),
        ),
    ]
