# Generated by Django 5.1 on 2025-01-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0019_alter_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='country',
            new_name='city',
        ),
    ]
