# Generated by Django 5.1 on 2025-01-29 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0020_rename_country_article_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomments',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='article_module.article'),
        ),
        migrations.AlterField(
            model_name='articlecomments',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
