# Generated by Django 5.1 on 2025-01-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0023_alter_articlecomments_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomments',
            name='parent',
        ),
    ]
