# Generated by Django 5.1 on 2024-10-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
