# Generated by Django 5.1 on 2024-11-02 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0005_post_likes_alter_postlikes_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlikes',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
