# Generated by Django 5.1 on 2025-01-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0008_post_likes_delete_postlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
