# Generated by Django 5.1 on 2025-01-13 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article_module', '0016_remove_article_saved_by_users_delete_savedarticles'),
        ('post_module', '0008_post_likes_delete_postlikes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='static/profile', verbose_name='profile picture')),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, verbose_name='telegram link')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, verbose_name='instagram link')),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True, verbose_name='linked-in link')),
                ('job', models.CharField(blank=True, max_length=50, null=True, verbose_name='your job')),
                ('about', models.TextField(blank=True, null=True, verbose_name='about you')),
                ('liked_posts', models.ManyToManyField(to='post_module.post')),
                ('saved_articles', models.ManyToManyField(to='article_module.article')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
