# Generated by Django 5.1 on 2025-02-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_module', '0002_profile_activity_score_alter_profile_liked_posts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='profile picture'),
        ),
    ]
